"""Add engine_id to Playlist model

Revision ID: a05b8f14f803
Revises: 
Create Date: 2025-07-04 07:25:06.157754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05b8f14f803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_id', sa.String(length=50), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_uri', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('artist_common_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('song',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('artist',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('playlist_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('playlist_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('engine_id')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('Playlist',
    sa.Column('playlist_dt', sa.DATE(), nullable=True),
    sa.Column('playlist_nm', sa.TEXT(), nullable=True),
    sa.Column('length', sa.INTEGER(), nullable=True),
    sa.Column('nbr_of_songs', sa.INTEGER(), nullable=True),
    sa.Column('recentadd_play_cnt', sa.DATE(), nullable=True),
    sa.Column('debug_level', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('pct', sa.INTEGER(), nullable=True),
    sa.Column('nbr_of_cat_songs', sa.INTEGER(), nullable=True),
    sa.Column('nbr_of_cat_playlist_songs', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('playlist_type', sa.TEXT(), nullable=True),
    sa.Column('ktunes_play_processed', sa.TEXT(), nullable=True)
    )
    with op.batch_alter_table('Playlist', schema=None) as batch_op:
        batch_op.create_index('idx_playlist', ['username', 'playlist_nm', 'category'], unique=1)

    op.create_table('playlist_song_play_counts',
    sa.Column('song', sa.TEXT(), nullable=True),
    sa.Column('artist_common_name', sa.TEXT(), nullable=True),
    sa.Column('playlist_play_cnt', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('song', 'artist_common_name')
    )
    op.create_table('_alembic_tmp_Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Playlist_tracks',
    sa.Column('playlist_dt', sa.DATE(), nullable=True),
    sa.Column('playlist_nm', sa.TEXT(), nullable=True),
    sa.Column('track_cnt', sa.INTEGER(), nullable=True),
    sa.Column('artist', sa.TEXT(), nullable=True),
    sa.Column('song', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('length', sa.INTEGER(), nullable=True),
    sa.Column('play_cnt', sa.INTEGER(), nullable=True),
    sa.Column('last_play_dt', sa.DATE(), nullable=True),
    sa.Column('cat_cnt', sa.INTEGER(), nullable=True),
    sa.Column('artist_cat_cnt', sa.INTEGER(), nullable=True),
    sa.Column('artist_common_name', sa.TEXT(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True)
    )
    with op.batch_alter_table('Playlist_tracks', schema=None) as batch_op:
        batch_op.create_index('idx_playlist_tracks', ['username', 'playlist_dt', 'playlist_nm', 'track_cnt', 'artist', 'song'], unique=1)

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.create_table('_alembic_tmp_tracks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('song', sa.VARCHAR(), nullable=True),
    sa.Column('artist', sa.VARCHAR(), nullable=True),
    sa.Column('album', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('play_cnt', sa.INTEGER(), nullable=True),
    sa.Column('played_sw', sa.VARCHAR(), server_default=sa.text('0'), nullable=True),
    sa.Column('artist_common_name', sa.VARCHAR(), nullable=True),
    sa.Column('ktunes_play_cnt', sa.INTEGER(), nullable=True),
    sa.Column('last_play_dt', sa.DATETIME(), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('ktunes_last_play_dt', sa.DATETIME(), nullable=True),
    sa.Column('most_recent_playlist', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
